import type { Metadata } from "next";
import { Zen_Dots } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { signOut } from "@/auth";
import Image from "next/image";
import { PhoneIcon , MapPinIcon, EnvelopeIcon} from "@heroicons/react/24/outline";

const zenDots = Zen_Dots({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-zen-dots',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={`${zenDots.variable} font-zen-dots`}>
        <nav className="flex justify-between items-center mx-auto px-4 sm:px-6 md:px-8 w-10/12">
          <div className="flex items-center">
            <Image src="/mainlogo.jpeg" alt="Mini Soccer" width={80} height={80} />
          </div>
          
          {/* Mobile menu button */}
          <div className="md:hidden">
            <button className="text-white focus:outline-none">
              <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              </svg>
            </button>
          </div>
          
          {/* Desktop menu */}
          <div className="hidden md:flex items-center space-x-4">
            {session ? (
              <>
                <span className="text-sm">Hello, {session.user.name || session.user.email}</span>
                <form action={async () => {
                  'use server';
                  await signOut();
                }}>
                  <button type="submit" className="bg-red-500 hover:bg-red-600 text-white px-4 py-2 rounded-md">
                    Logout
                  </button>
                </form>
              </>
            ) : (
              <>
                <a href="/" className="text-white hover:text-orange-500">Home</a>
                <a href="/" className="text-white hover:text-orange-500">Booking</a>
                <a href="/login" className="text-white hover:text-orange-500">Login</a>
                <a href="/register" className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-md">Register</a>
              </>
            )}
          </div>
        </nav>
        {children}
        <footer className="bg-gray-800 text-white py-4">
          <div className="container mx-auto px-4 sm:px-6 md:px-8 flex items-center w-10/12 py-10">
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 gap-9 w-full">
              <div className="w-full">
                <Image src="/mainlogo.jpeg" alt="Mini Soccer" width={80} height={80} />
                <h3 className="text-3xl font-bold mt-10">Johor Mini Soccer</h3>
                <ul className="mt-2 space-y-2">
                  <li><a href="/" className="hover:text-orange-500">Home</a></li>
                  <li><a href="/" className="hover:text-orange-500">Booking</a></li>
                </ul>
              </div>
              <div className="w-full">
                <h3 className="text-3xl font-bold">Contact Us</h3>
                <ul className="mt-2 space-y-2">
                  <li><a href="/" className="hover:text-orange-500 flex items-center">
                    <PhoneIcon className="h-7 w-7 mr-5" /> Whatssap: 012-3456789</a></li>
                  <li>
                    <a href="/" className="hover:text-orange-500 flex items-center">
                    <MapPinIcon className="h-7 w-7 mr-5" /> 
                    Address: Medan Johor, Indonesia</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
              <div className="w-full flex justify-center items-center">
                <p className="mt-2 text-gray-400 text-xs">
                  © {new Date().getFullYear()} Johor Mini Soccer. All rights reserved.
                </p>
              </div>
        </footer>
      </body>
    </html>
  );
}
